# Generated by Django 5.2.17 on 2026-08-10 13:38

import apps.profiles.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyStack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('BACKEND_DEVELOPER', 'Backend Developer'), ('FRONTEND_DEVELOPER', 'Frontend Developer'), ('PRODUCT_DESIGNER', 'Product Designer')], max_length=32, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('code__in', ['BACKEND_DEVELOPER', 'FRONTEND_DEVELOPER', 'PRODUCT_DESIGNER'])), name='profiles_role_known_code')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(blank=True, max_length=64, validators=[apps.profiles.validators.validate_timezone_name])),
                ('language', models.CharField(blank=True, max_length=35)),
                ('interests', models.JSONField(blank=True, default=list, validators=[apps.profiles.validators.validate_interests])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='profiles.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='ProfileLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_type', models.CharField(choices=[('PROFILE', 'Profile'), ('PROJECT', 'Project'), ('PORTFOLIO', 'Portfolio'), ('CASE_STUDY', 'Case study')], max_length=16)),
                ('url', models.URLField(max_length=500)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='profiles.userprofile')),
            ],
            options={
                'ordering': ['position', 'created_at', 'id'],
                'indexes': [models.Index(fields=['profile', 'link_type', 'position'], name='profiles_link_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'url'), name='profiles_link_profile_url_unique')],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profiles.userprofile')),
                ('technology_stack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_skills', to='profiles.technologystack')),
            ],
            options={
                'ordering': ['technology_stack__name'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'technology_stack'), name='profiles_skill_profile_stack_unique')],
            },
        ),
    ]
