# Generated by Django 5.2.17 on 2026-08-13 10:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_seed_known_roles_and_stacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'ordering': ['number'],
                'constraints': [models.CheckConstraint(condition=models.Q(('number__in', (1, 2, 3))), name='projects_level_known_number')],
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_templates', to='projects.level')),
            ],
            options={
                'ordering': ['level__number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('summary', models.TextField(blank=True)),
                ('duration_weeks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sprint_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weekly_effort_hours_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weekly_effort_hours_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('participant_database', models.CharField(blank=True, max_length=120)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='projects.projecttemplate')),
            ],
            options={
                'ordering': ['project_template_id', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_work_items', to='profiles.role')),
                ('technology_stack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_work_items', to='profiles.technologystack')),
                ('project_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='projects.projectversion')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRoleRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requires_stack', models.BooleanField(default=True)),
                ('stack_policy', models.CharField(blank=True, choices=[('FIXED', 'Fixed'), ('ALLOWLIST', 'Allowlist'), ('OPEN', 'Open')], max_length=16, null=True)),
                ('context', models.TextField(blank=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_requirements', to='profiles.role')),
                ('project_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requirements', to='projects.projectversion')),
            ],
            options={
                'ordering': ['role__name'],
            },
        ),
        migrations.CreateModel(
            name='RolePrerequisite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('role_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='projects.projectrolerequirement')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRoleAllowedStack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('technology_stack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_role_allowances', to='profiles.technologystack')),
                ('role_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_stacks', to='projects.projectrolerequirement')),
            ],
            options={
                'ordering': ['technology_stack__name'],
                'constraints': [models.UniqueConstraint(fields=('role_requirement', 'technology_stack'), name='projects_allowed_stack_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='projectversion',
            index=models.Index(fields=['project_template', 'published_at', '-version_number'], name='projects_version_public_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectversion',
            constraint=models.UniqueConstraint(fields=('project_template', 'version_number'), name='projects_version_template_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='projectversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='projects_version_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='projectversion',
            constraint=models.CheckConstraint(condition=models.Q(('weekly_effort_hours_min__isnull', True), ('weekly_effort_hours_max__isnull', True), ('weekly_effort_hours_min__lte', models.F('weekly_effort_hours_max')), _connector='OR'), name='projects_version_effort_range_valid'),
        ),
        migrations.AddIndex(
            model_name='projecttasktemplate',
            index=models.Index(fields=['project_version', 'role', 'technology_stack', 'position'], name='projects_work_item_context_idx'),
        ),
        migrations.AddConstraint(
            model_name='projecttasktemplate',
            constraint=models.UniqueConstraint(fields=('project_version', 'role', 'technology_stack', 'position'), name='projects_work_item_scope_position_unique', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='projecttasktemplate',
            constraint=models.CheckConstraint(condition=models.Q(('technology_stack__isnull', True), ('role__isnull', False), _connector='OR'), name='projects_work_item_stack_requires_role'),
        ),
        migrations.AddConstraint(
            model_name='projectrolerequirement',
            constraint=models.UniqueConstraint(fields=('project_version', 'role'), name='projects_requirement_version_role_unique'),
        ),
        migrations.AddConstraint(
            model_name='projectrolerequirement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('requires_stack', True), ('stack_policy__in', ['FIXED', 'ALLOWLIST', 'OPEN'])), models.Q(('requires_stack', False), ('stack_policy__isnull', True)), _connector='OR'), name='projects_requirement_stack_policy_valid'),
        ),
        migrations.AddConstraint(
            model_name='roleprerequisite',
            constraint=models.UniqueConstraint(fields=('role_requirement', 'position'), name='projects_prerequisite_position_unique'),
        ),
    ]
