# Generated by Django 5.2.17 on 2026-08-13 13:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_seed_known_roles_and_stacks'),
        ('projects', '0002_seed_known_project_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=160)),
                ('brief', models.TextField(blank=True)),
                ('planned_start_offset_days', models.PositiveIntegerField()),
                ('planned_duration_days', models.PositiveIntegerField()),
                ('project_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_templates', to='projects.projectversion')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddField(
            model_name='projecttasktemplate',
            name='sprint_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_items', to='projects.sprinttemplate'),
        ),
        migrations.AddIndex(
            model_name='projecttasktemplate',
            index=models.Index(fields=['sprint_template', 'position'], name='projects_work_item_sprint_idx'),
        ),
        migrations.AddIndex(
            model_name='sprinttemplate',
            index=models.Index(fields=['project_version', 'sequence'], name='projects_sprint_schedule_idx'),
        ),
        migrations.AddConstraint(
            model_name='sprinttemplate',
            constraint=models.UniqueConstraint(fields=('project_version', 'sequence'), name='projects_sprint_version_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='sprinttemplate',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='projects_sprint_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='sprinttemplate',
            constraint=models.CheckConstraint(condition=models.Q(('planned_duration_days__gte', 1)), name='projects_sprint_duration_positive'),
        ),
    ]
