# Generated by Django 5.2.17 on 2026-08-13 17:02

import datetime
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_roletechnologystack'),
        ('projects', '0004_project_definition_integrity_triggers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamFormation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ready_confirmed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_team_formations', to=settings.AUTH_USER_MODEL)),
                ('project_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_formations', to='projects.projectversion')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReadyCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('is_current', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('expires_at', models.DateTimeField(editable=False)),
                ('responded_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_ready_checks', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ready_checks', to='profiles.role')),
                ('technology_stack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ready_checks', to='profiles.technologystack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ready_checks', to=settings.AUTH_USER_MODEL)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ready_checks', to='formations.teamformation')),
            ],
            options={
                'ordering': ['formation_id', 'role__name', 'started_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='teamformation',
            index=models.Index(fields=['project_version', 'ready_confirmed_at'], name='formations_version_ready_idx'),
        ),
        migrations.AddIndex(
            model_name='readycheck',
            index=models.Index(fields=['user', 'is_current', 'status', 'expires_at'], name='formations_user_ready_idx'),
        ),
        migrations.AddConstraint(
            model_name='readycheck',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('formation', 'role'), name='formations_current_role_unique'),
        ),
        migrations.AddConstraint(
            model_name='readycheck',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('formation', 'user'), name='formations_current_user_unique'),
        ),
        migrations.AddConstraint(
            model_name='readycheck',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED', 'DECLINED', 'EXPIRED'])), name='formations_ready_status_known'),
        ),
        migrations.AddConstraint(
            model_name='readycheck',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at', django.db.models.expressions.CombinedExpression(models.F('started_at'), '+', models.Value(datetime.timedelta(days=2))))), name='formations_ready_expiry_48h'),
        ),
        migrations.AddConstraint(
            model_name='readycheck',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('responded_at__isnull', True), ('status', 'PENDING')), models.Q(('responded_at__isnull', True), ('status', 'EXPIRED')), models.Q(('responded_at__isnull', False), ('status__in', ('CONFIRMED', 'DECLINED'))), _connector='OR'), name='formations_ready_response_coherent'),
        ),
    ]
