# Generated by Django 5.2.17 on 2026-09-06 16:30

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formations", "0007_referenced_project_version_integrity"),
        ("profiles", "0003_roletechnologystack"),
        ("projects", "0008_populate_helpdesk_l1_full_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectReadiness",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                (
                    "consumed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "project_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_readinesses",
                        to="projects.projectversion",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_readinesses",
                        to="profiles.role",
                    ),
                ),
                (
                    "technology_stack",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_readinesses",
                        to="profiles.technologystack",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_readinesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("consumed_at__isnull", True)),
                        fields=("user",),
                        name="formations_active_readiness_user_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("consumed_at__isnull", True),
                            ("consumed_at__gte", models.F("created_at")),
                            _connector="OR",
                        ),
                        name="formations_readiness_consumed_after_created",
                    ),
                ],
            },
        ),
    ]
